# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you have one
# github: [u9401066]

# Other funding platforms (uncomment and fill in if applicable)
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name
# community_bridge: # Replace with a single Community Bridge project-name
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name
# polar: # Replace with a single Polar username

custom: # Replace with up to 4 custom sponsorship URLs
# custom: ['https://www.buymeacoffee.com/your_username']
